In [12]:
import deepxde as dde
from deepxde.backend import tf

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
torch.cuda.is_available()

True

In [5]:
x = torch.ones(3, device=torch.device("cuda"))

In [6]:
x

tensor([1., 1., 1.], device='cuda:0')

In [7]:
x = x.to("cpu")

In [8]:
x

tensor([1., 1., 1.])

In [9]:
y = x.numpy()

In [10]:
y

array([1., 1., 1.], dtype=float32)

In [11]:
z = torch.tensor(y, device=torch.device("cpu"))
z

tensor([1., 1., 1.])

Back Propogation